name: Deploy Storybook Preview

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Build Storybook
        run: npm run storybook:build

      - name: Deploy to production
        if: github.event_name == 'push'
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          wranglerVersion: "4.78.0"

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        id: preview
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload --message "PR #${{ github.event.pull_request.number }} @ ${{ github.event.pull_request.head.sha }}"
          wranglerVersion: "4.78.0"

      - name: Comment preview URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v9
        env:
          DEPLOYMENT_URL: ${{ steps.preview.outputs.deployment-url }}
        with:
          script: |
            const { postComment } = await import('${{ github.workspace }}/.github/workflows/helpers/post-deploy-preview-github-comment.js')

            await postComment({ github, context, core });
